### ISSUE TITLE
pyMARS dependencies not checked / incomplete

### ISSUE THREAD

**Issue by arghdos** [Niemeyer-Research-Group/pyMARS#7]
To reproduce:

Using `python 2.7.15` via conda:

Run `pip install .`

As far as I can tell the following are required:

```
cantera
numpy
h5py
matplotlib
networkx
```

Notably matplotlib is missing from the `setup.py` file.  Additionally, pip let me install pyMARS without any of these installed in my Conda env for some reason...

**Comment by kyleniemeyer** [comment]
Would you try this again with the newest version? `setup.py` *should* have all the actual necessary dependencies now.

**Comment by arghdos** [comment]
@kyleniemeyer so there are a couple of issues remaining (#9) fixes a syntax error in the setup.py.
Further, when I try to run the example in the README to test:
```
python pymars.py --file ../example_files/gri30.cti --run_drgep --conditions ../example_files/example_input_file.txt --species CH4,O2,N2,CO2,H2O --error 5 --target CH4,O2
```

I get the error:

```
PyTables must be installed
Traceback (most recent call last):
  File "pymars.py", line 2, in <module>
    from home import readin
  File "/home/nick/pyMARS/pymars/home.py", line 8, in <module>
    from drgep import run_drgep
  File "/home/nick/pyMARS/pymars/drgep.py", line 9, in <module>
    from simulation import Simulation
  File "/home/nick/pyMARS/pymars/simulation.py", line 19, in <module>
    import tables
ModuleNotFoundError: No module named 'tables'
```

After I install that via conda, and try to run the example again, I get:

```
Traceback (most recent call last):
  File "pymars.py", line 2, in <module>
    from home import readin
  File "/home/nick/pyMARS/pymars/home.py", line 11, in <module>
    from sensativity_analysis import run_sa
ModuleNotFoundError: No module named 'sensativity_analysis'
```

(which is a simple misspelling)

After fixing that, there is some sort of HDF5 error:
```
Traceback (most recent call last):
  File "pymars.py", line 138, in <module>
    m()
  File "pymars.py", line 98, in m
    readin(args)
  File "/home/nick/pyMARS/pymars/home.py", line 124, in readin
    reduced = run_drgep(args, solution_object,error,past)
  File "/home/nick/pyMARS/pymars/drgep.py", line 159, in run_drgep
    ignition_delay_detailed = helper.simulate(sim_array) #Run simulations and process results
  File "/home/nick/pyMARS/pymars/helper.py", line 43, in simulate
    tau.append(case.run_case())
  File "/home/nick/pyMARS/pymars/simulation.py", line 95, in run_case
    title=str(self.idx)
  File "/home/nick/miniconda3/envs/pyMARS/lib/python3.7/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/nick/miniconda3/envs/pyMARS/lib/python3.7/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 371, in tables.hdf5extension.File._g_new
  File "/home/nick/miniconda3/envs/pyMARS/lib/python3.7/site-packages/tables/utils.py", line 175, in check_file_access
    raise IOError("``%s`` does not exist" % (parentname,))
OSError: ``./h5files`` does not exist
```

I would also recommend:

1.  Fixing the readme example to read:

```
python pymars.py --file ../example_files/gri30.cti --run_drgep --conditions ../example_files/example_input_file.txt --species CH4,O2,N2,CO2,H2O --error 5 --target CH4,O2
```

(note capitalization change in python file), and  

2.  Add an `__init__.py` and a simple `__main__.py` wrapper around `pymars.py` such that pyMARS can be called as a module, e.g.:

```
python -m pymars --file ../example_files/gri30.cti --run_drgep --conditions ../example_files/example_input_file.txt --species CH4,O2,N2,CO2,H2O --error 5 --target CH4,O2
```

for when it's already installed.
