### ISSUE TITLE
Error running simple mechanism reduction case

### ISSUE THREAD

**Issue by Zyr1ak** [Niemeyer-Research-Group/pyMARS#88]
Hello,

I have started using cantera and pymars for a couple of days so it is still a code i am unfamiliar with. For a project, i need to reduce some complex mechanism for biomass pyrolysis using CRECK database. While i ran the chemical mechanism reduction command for the simple tutorial case available on the website : pymars --input reduction_input.yaml using the same procedure as the website I see the following error: 
Traceback (most recent call last):
  File "/home/adil/anaconda3/bin/pymars", line 8, in <module>
    from pymars.__main__ import main
  File "/home/adil/anaconda3/lib/python3.12/site-packages/pymars/__main__.py", line 4, in <module>
    from .pymars import pymars
  File "/home/adil/anaconda3/lib/python3.12/site-packages/pymars/pymars.py", line 19, in <module>
    from .tools import convert
  File "/home/adil/anaconda3/lib/python3.12/site-packages/pymars/tools.py", line 9, in <module>
    from cantera import ck2cti
ImportError: dynamic module does not define module export function (PyInit_ck2cti).

The mistake probably might be silly and come from me. I thought that it might come from installation or python version but didn't work out. I am too unfamiliar with the code to look into it in detail either. (tried unsucessfully).

Please kindly help.

**Comment by kreto7** [comment]
Hello, I have encountered the same problem as you. Have you solved it? How did you solve it? Thank you very much.

**Comment by Zyr1ak** [comment]
Hello, yes I managed to solve it somehow.

I created two different environments, one running python 9.6 to use pymars
module options and one using python 9.12 to use pure cantera problems.

Using that I managed to make the cases work.

Best regards,
Adil

**Comment by kyleniemeyer** [comment]
@Zyr1ak @kreto7 pyMARS has just been updated to v1.2.0, which is compatible with Python 3.10+ and modern Cantera. This should address the issues you were facing
